theme: jekyll-theme-cayman

# Setup
title: Laravel File Manager
description: It's like Dropbox for your Laravel app.
google_analytics:

# About/contact
author:
  name: Mafftor
  url: https://github.com/mafftor
